name: 'Run jsDelivr-Purge'

on:
  schedule:
    - cron: '0 0/1 * * *'
  workflow_dispatch:
    inputs:
      delay:
        required: true
        type: string
      branches:
        required: true
        type: string
      

permissions:
    actions: read
    contents: read

jobs:
    jsdelivrpurge:
        runs-on: ubuntu-latest
        steps:
            - name: Run jsDelivr-Purge
              uses: List-KR/jsdelivr-purge@v4
              with:
                branches: "master"
