name: AGLint

on:
    push:
        branches-ignore:
            - master
    pull_request:
        branches:
            - "**"

jobs:
    lint:
        name: Run AGLint
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   name: Check out to repository
                uses: actions/checkout@v7

            -   name: Set up Bun
                uses: oven-sh/setup-bun@v2

            -   name: Install dependencies
                run: bun install

            -   name: Run AGLint
                run: bun run lint
