name: AGLint

on:
    push:
        branches-ignore:
            - master
    pull_request:
        branches:
            - "**"

jobs:
    lint:
        name: Run AGLint
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   name: Check out to repository
                uses: actions/checkout@v7

            -   name: Set up pnpm
                uses: pnpm/setup@v2
                with:
                    runtime: node@latest
                    cache: true

            -   name: Run AGLint
                run: pnpm run lint
