name: Publish and Deploy

on:
    push:
        branches: [ master ]
    workflow_dispatch:

concurrency:
    group: publish-and-deploy
    cancel-in-progress: false

jobs:
    lint:
        name: Run AGLint
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   name: Check out to repository
                uses: actions/checkout@v7

            -   name: Set up pnpm
                uses: pnpm/setup@v2
                with:
                    version: 11
                    runtime: node@latest
                    cache: true

            -   name: Install dependencies
                run: pnpm install

            -   name: Run AGLint
                run: pnpm run lint

    build:
        name: Build and Publish to npm
        needs: lint
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            -   name: Check out to repository
                uses: actions/checkout@v7

            -   name: Set up pnpm
                uses: pnpm/setup@v2
                with:
                    runtime: node@latest
                    cache: true

            -   name: Build
                run: pnpm run build

            -   name: Set up Node.js
                uses: actions/setup-node@v7
                with:
                    node-version: latest

            -   name: Publish to npm
                run: npm publish

    purge:
        name: Purge jsdelivr cache
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   name: Purge jsdelivr cache
                uses: FilteringDev/jsdelivr-purge-npm@0bee790e911f359243cd8d98cd87f6bbbc879e80
                with:
                    package: @list-kr/filterslists
                    disttag: latest
