name: 'Run SelfRandom'

on:
  schedule:
    - cron: '* 0/4 * * *'
  workflow_dispatch:

jobs:
  SelfRandom:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Link NPM packages
        run: |
          npm link typescript
          npm link @types/node
          npm link @actions/core
          npm link @octokit/rest
      - name: Run SelfRandom
        uses: List-KR/selfrandom@v1.0.1
        with:
          gitHubtoken: ${{ github.token }}
          reponame: ${{ github.repository }}
      - name: Cleanup
        run: rm -r *
