name: AGLint and jsDelivr

on:
  push:
    branches:
      - '**'

permissions:
    actions: read
    contents: read

jobs:
  lint:
    name: Run AGLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run AGLint
        run: npm run lint
  
  jsdelivrpurge:
    name: Purge jsDelivr cache
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ always() && github.event_name == 'push' && github.ref_name == 'master' && needs.lint.result == 'success' }}
    steps:
      - name: Run jsDelivr-Purge
        uses: List-KR/jsdelivr-purge@v4
        with:
          branches: "master"